// Builds the page-transition mask: a horizontal sprite of FRAMES frames in which broad brush strokes sweep across
// the screen, alternating direction, until it is fully painted. White = new page shows. The CSS steps through it.
// node scripts/brush-reveal.mjs  ->  public/transitions/brush-reveal.png
import sharp from 'sharp';

const FRAMES = 24, W = 360, H = 240;
// each stroke: a band across the screen (y and thickness as fractions of H), the way it travels, a slight tilt
const strokes = [
  { y: 0.1, t: 0.3, dir: 1, tilt: 0.08 },
  { y: 0.34, t: 0.32, dir: -1, tilt: -0.06 },
  { y: 0.58, t: 0.32, dir: 1, tilt: 0.07 },
  { y: 0.84, t: 0.34, dir: -1, tilt: -0.05 },
  { y: 0.22, t: 0.26, dir: 1, tilt: -0.04 },
  { y: 0.7, t: 0.28, dir: -1, tilt: 0.05 },
];
const START = (i) => i * 0.14; // stagger: the last stroke lands on the final frame
const DUR = 0.3; // each stroke's share of the whole transition
const ease = (x) => 1 - (1 - x) ** 2.4;
// seeded random, so the sprite is the same every build
let seed = 7;
const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
// every stroke is a brush of BRISTLES hairs: each hair has its own length and wobble, so the edges and the tail
// break up like dry paint instead of ending on a clean line
const BRISTLES = 22;
const hairs = strokes.map(() => Array.from({ length: BRISTLES }, (_, j) => ({
  off: (j / (BRISTLES - 1) - 0.5) + (rnd() - 0.5) * 0.04, // across the band, -0.5..0.5
  reach: 0.78 + rnd() * 0.22 - Math.abs(j / (BRISTLES - 1) - 0.5) * 0.35, // outer hairs run out of paint sooner
  lag: rnd() * 0.08,
  w: 1.3 + rnd() * 1.1,
  phase: rnd() * 6,
})));

function hairPath(s, h, progress) {
  const n = 28, len = 1.62 * Math.max(0, progress * h.reach - h.lag);
  if (len <= 0) return '';
  const pts = [];
  for (let k = 0; k <= n; k++) {
    const u = (k / n) * len - 0.18; // starts off-screen, overshoots the far edge
    const x = (s.dir > 0 ? u : 1 - u) * W;
    const cy = s.y + s.tilt * (u - 0.5) + 0.02 * Math.sin(u * 8 + s.y * 9);
    const y = (cy + h.off * s.t + 0.006 * Math.sin(u * 23 + h.phase)) * H;
    pts.push(`${x.toFixed(1)} ${y.toFixed(1)}`);
  }
  return `<path d="M${pts.join(' L')}" stroke="#fff" stroke-width="${((s.t * H) / BRISTLES * h.w * 1.6).toFixed(2)}" stroke-linecap="round" fill="none"/>`;
}

const frames = [];
for (let f = 0; f < FRAMES; f++) {
  const p = f / (FRAMES - 1);
  let body = '';
  if (f === FRAMES - 1) body = `<rect width="${W}" height="${H}" fill="#fff"/>`;
  else strokes.forEach((s, i) => {
    const local = Math.max(0, Math.min(1, (p - START(i)) / DUR));
    if (local <= 0) return;
    for (const h of hairs[i]) body += hairPath(s, h, ease(local));
  });
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}"><rect width="${W}" height="${H}" fill="#000"/>${body}</svg>`;
  frames.push(await sharp(Buffer.from(svg)).extractChannel('red').raw().toBuffer({ resolveWithObject: true }));
}
// strokes overlap, so the screen is full before the timeline ends: stop at the first fully painted frame
const full = frames.findIndex(({ data }) => data.reduce((n, v) => n + (v > 127 ? 1 : 0), 0) >= W * H * 0.995);
if (full > 0) frames.length = full + 1;
frames[frames.length - 1].data.fill(255); // the last frame is the whole new page
const N = frames.length;
// assemble: white channel becomes alpha
const sprite = Buffer.alloc(W * N * H * 4);
frames.forEach(({ data }, f) => {
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    const v = data[y * W + x];
    const o = (y * W * N + f * W + x) * 4;
    sprite[o] = sprite[o + 1] = sprite[o + 2] = 0; sprite[o + 3] = v;
  }
});
await sharp(sprite, { raw: { width: W * N, height: H, channels: 4 } }).png({ compressionLevel: 9, palette: true }).toFile('public/transitions/brush-reveal.png');
// the frame count drives the CSS (mask size, steps), and steps() takes only a literal number, so the whole
// transition stylesheet is written here
const { writeFileSync } = await import('node:fs');
writeFileSync('src/styles/brush-transition.css', `/* Generated by scripts/brush-reveal.mjs (${N} frames): edit the script, not this file.
   Page changes paint the new page in with brush strokes: a cross-document view transition whose new snapshot is
   revealed through the brush sprite. Browsers without view transitions just navigate. Reduced motion: none. */
@media (prefers-reduced-motion: no-preference) {
  @view-transition { navigation: auto; }
  /* the nav stays put while the page under it is painted */
  .nav { view-transition-name: site-nav; }
  ::view-transition-group(site-nav) { animation: none; }
  ::view-transition-old(root) { animation: none; }
  ::view-transition-new(root) {
    -webkit-mask-image: url(/transitions/brush-reveal.png); mask-image: url(/transitions/brush-reveal.png);
    -webkit-mask-size: ${N * 100}% 100%; mask-size: ${N * 100}% 100%;
    -webkit-mask-repeat: no-repeat; mask-repeat: no-repeat;
    animation: brush-paint 0.95s steps(${N}, jump-none) both;
  }
}
@keyframes brush-paint {
  from { -webkit-mask-position: 0% 0; mask-position: 0% 0; }
  to { -webkit-mask-position: 100% 0; mask-position: 100% 0; }
}
`);
console.log('public/transitions/brush-reveal.png', W * N, 'x', H, `(${N} frames)`);
